### ISSUE TITLE
Add configurable icon for Services

### ISSUE THREAD

**Issue by StephenOTT** [DigitalState/Portal#44]
![screen shot 2017-09-07 at 8 04 34 pm](https://user-images.githubusercontent.com/1994838/30190460-3ea80bf6-9408-11e7-92c3-5689573f03ff.png)

see https://github.com/DigitalState/Services/issues/28 for dependency.

Lets store the icon information in `data.icon`

**Comment by StephenOTT** [comment]
Note: The field will be translatable

**Comment by StephenOTT** [comment]
added today as per @baddlan.
But does not work.  @baddlan was this tested?
![screen shot 2017-09-27 at 7 59 07 pm](https://user-images.githubusercontent.com/1994838/30943346-6a678ada-a3be-11e7-98e4-c88d9453e05c.png)

admin:
![screen shot 2017-09-27 at 7 59 53 pm](https://user-images.githubusercontent.com/1994838/30943353-7672bc28-a3be-11e7-90f7-1a6f4fb0ae88.png)

Appears the data field is not returned?  @mario-digitalstate can you confirm that Services list application/hal+json returns the data field ?

**Comment by marioprudhomme** [comment]
Will need to add it to individual/anonymous read permissions.

Also if you can use normal constant strings instead of actual FA class names, that would be better since we wouldn't be tied to FA. Example: "search" instead of "fa-search". In the ui, you can either switch-case or programmatically transform the string into a FA class name. It's a concern of the theme, not the backend.

P.s. we can use the FA class names (minus the FA part) for the constant strings to keep things simple.

**Comment by baddlan** [comment]
Actually, that's exactly how it works right now. I have `fa-` prepended to the class name so the `icon` field should only contain `paint-brush` for example.

**Comment by StephenOTT** [comment]
@baddlan  has the comment from @mario-digitalstate been completed?

>Will need to add it to individual/anonymous read permissions.
